AllCops:
  TargetRubyVersion: 2.5
  UseCache: false
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https
  Enabled: true

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 25

Style/TrailingCommaInArguments:
  Description: 'Checks for trailing comma in argument lists.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-params-comma'
  Enabled: true
  EnforcedStyleForMultiline: comma